### ISSUE TITLE
Binary size

### ISSUE THREAD

**Issue by lollita** [lomo74/mfilemon#5]
Why the last version size is more than double that 1.5.2 again working?

**Comment by lomo74** [comment]
DLLs are bigger, and the installer contains all of them (x86+x64, English+Italian), so a 500K increase for each results in an 2MB increase of the overall size. Version 1.5.2 is 6 years old, some new features have been added since then. Is such increase in size an issue for you?

**Comment by lollita** [comment]
I don't refer to all zipped pack but to driver only.
The last version size is more than double that 1.5.2
I don't see big changes between 1.6.1 and 1.5.2.
And then it is better to keep the smallest that works perfectly.
Maybe you used some parameter that enlarges the file?
I see that old have dependecies on vcruntime140.dll and new not.
Maybe you have compiled statically-link?

**Comment by lomo74** [comment]
Yes, v. 1.6.1 is linked against the static CRT and libcrypto, this could be the cause of the increased size. I have added some bugfixes in the latest versions, I see no reason to stick with the old versions, besides that of being on severe RAM shortage. That's up to you.

**Comment by lollita** [comment]
Old have two dependencies to vcruntime140.dll int two dll.
I suppose that instead New repeat two same static binary in two different dll.
Do it is possible to try to do available a dinamyc dll version?
What it the function of libcrypto in a pdf printer? the Old not have it.

**Comment by lomo74** [comment]
For user password encryption, have a look at
https://github.com/lomo74/mfilemon/blob/main/monitor/portlist.cpp

No, I'm not going to revert to dynamic CRT linking. There is no benefit in doing this, and the installer would require to include and launch the VC runtime setup. Please consider forking the project if you absolutely need smaller binaries.

**Comment by lollita** [comment]
I not ask to revert but do add option as f.e. FFMPEG too does.
Download static and dinamyc binary. At least for test.
To compile do it need Driver Kit (WDK)?
