### ISSUE TITLE
Insufficient file for build

### ISSUE THREAD

**Issue by x1turbo** [lomo74/mfilemon#9]
Hi, I'm using mfilemon in my Company.

For support, I'm going to build modules and setup, but there are some insufficient file.
1. When build by VS, there isn't Post build event command, D:\proj\firma\firma.bat "$(TargetDir)$(TargetFileName)".
2. Build mfilemon.iss by Inno Setup, following error occured. Maybe lorenzomonti is absent.
  SignTool=lorenzomonti /d "{#AppName}"

Can you add there files in project?
I would appreciate it if you would consider it.

Thanks.

**Comment by lomo74** [comment]
Hello, both directives have to do with my digital signature. Just remove them if you're building a custom setup.

**Comment by x1turbo** [comment]
Thanks!
I will replace them by our digital sign procedure.
